name: Generate TypeScript Protobuf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'

    - name: Install protobuf compiler
      run: sudo apt-get install -y protobuf-compiler

    - name: Install TypeScript plugins
      run: npm install -g ts-protoc-gen

    - name: Run Makefile
      run: make ts