name: Publish Go Module

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for tags

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Install protobuf compiler
        run: sudo apt-get install -y protobuf-compiler
    
      - name: Install Go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate Go code
        run: |
          make go

      - name: Commit and push generated code
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add gen/go
          git commit -m "Add generated Go code for $GITHUB_REF"
          git push origin HEAD:${GITHUB_REF}