name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'

    - name: Install protobuf compiler
      run: sudo apt-get install -y protobuf-compiler

    - name: Install Go plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Install Python plugins
      run: pip install grpcio-tools

    - name: Install TypeScript plugins
      run: npm install -g ts-protoc-gen

    - name: Install Java plugins
      run: |
        curl -L -o protoc-gen-grpc-java.jar https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.68.2/protoc-gen-grpc-java-1.68.2.jar
        mv protoc-gen-grpc-java.jar $HOME/bin/protoc-gen-grpc-java
        chmod +x $HOME/bin/protoc-gen-grpc-java

    - name: Run Makefile
      run: make all